;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
;
;  Written by Steward_Fu (steward.fu@gmail.com)
;  https://steward-fu.github.io/website/index.htm
;  
;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
;//typedef VOID (*WDFFUNC) (VOID);
;//extern WDFFUNC WdfFunctions [];
WDFFUNC typedef proto WDFAPI
PWDFFUNC typedef ptr WDFFUNC
extern WdfFunctions:proc
