//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
// file generated by the wizard

#ifndef __CHARACTERISTICS_H__
#define __CHARACTERISTICS_H__

// Declare Optional NDIS MiniportXxx handlers this driver supports

KNDIS_MINIPORT_HANDLER(I1394Adapter, CheckForHang)
KNDIS_MINIPORT_HANDLER(I1394Adapter, Send)
KNDIS_MINIPORT_HANDLER(I1394Adapter, ReturnPacket)
	
// Driver version
#define	I1394_VERSION_MAJOR			1
#define	I1394_VERSION_MINOR			0

// Medium Specific

#define KNDIS_MEDIUM_INCLUDE_802_3	/* forces OID handlers inclusion */
#define	I1394_MEDIUM_TYPE			NdisMedium802_3
#define	I1394_802_3_MAX_LIST_SIZE	32 /* NDIS Test requirement (>=) */				

// OID Constants
#define	I1394_MAX_LINKSPEED		100000000L

#define	I1394_MAX_SEND_PACKETS	1

#define	I1394_VENDOR_DESCRIPTION	"I1394 NDIS Miniport Driver"

// TODO: 
// Add other #defines and/or KNdisAdapterTraits<I1394Adapter> specializations as needed
#endif // __CHARACTERISTICS_H__
 