//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
// i1394.cpp - source file generated by NetDrvWizard. Contains
//				  KNdisMiniDriver-derived implementation
//				  

#include "I1394Drv.h"
#include "I1394Adap.h"

///////////////////////////////////////////////////////////////////
// Begin INIT time code
//
// Code in section INIT is discarded after the driver initializes
//#pragma code_seg("INIT")


// The following macro declares the driver class:

DECLARE_MINIDRIVER_CLASS(I1394Driver)

//////////////////////////////////////////////////////////////////////
// I1394Driver	Implementation

/////////////////////////////////////////////////////////////////////
// I1394Driver::DriverEntry
//
// This method registers adapter characteristics (a handler pointer table)
// with NDIS. Usually that's all this function has to do.
//
// Returns:
//	Status code of registration. Usually, it's NDIS_STATUS_SUCCESS.
//  Returning any other code prevents the driver from being loaded.
NTSTATUS I1394Driver::DriverEntry(IN PVOID)
{
	TRACE("I1394Driver::DriverEntry\n");

	KNDIS_MINIPORT_CHARACTERISTICS<I1394Adapter> Chars;
	return	Chars.Register(*this);	
}

 