//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
// file generated by the wizard

#ifndef __CHARACTERISTICS_H__
#define __CHARACTERISTICS_H__

// Declare Optional NDIS MiniportXxx handlers this driver supports

KNDIS_MINIPORT_HANDLER(WdmVNICAdapter, CheckForHang)
KNDIS_MINIPORT_HANDLER(WdmVNICAdapter, Send)
KNDIS_MINIPORT_HANDLER(WdmVNICAdapter, ReturnPacket)
#if defined(NDIS51_MINIPORT)
KNDIS_MINIPORT_HANDLER(WdmVNICAdapter, CancelSendPackets)
#endif
	

// Driver version
#define	WDMVNIC_VERSION_MAJOR			1
#define	WDMVNIC_VERSION_MINOR			1

// Medium Specific

#define KNDIS_MEDIUM_INCLUDE_802_3		/* forces OID handlers inclusion */
#define	WDMVNIC_MEDIUM_TYPE			NdisMedium802_3 
#define	WDMVNIC_802_3_MAX_LIST_SIZE	32 /* NDIS Test requirement (>=) */				


// OID Constants
#define	WDMVNIC_MAX_LOOKAHEAD		256
#define	WDMVNIC_MAX_FRAMESIZE		1500		// w/o header
#define	WDMVNIC_MAX_TOTAL_SIZE		1514		// incl. header
#define	WDMVNIC_MAX_LINKSPEED		10000000L
#define	WDMVNIC_TRANSMIT_BLOCK		256
#define	WDMVNIC_RECEIVE_BLOCK		256

#define WDMVNIC_TX_BUFFER_SPACE	16000				
#define WDMVNIC_RX_BUFFER_SPACE	16000

#define	WDMVNIC_MAX_SEND_PACKETS	4


#define	WDMVNIC_VENDOR_DESCRIPTION	"WDMVNIC NDIS Miniport Driver"

// TODO: 
// Add other #defines and/or KNdisAdapterTraits<WdmVNICAdapter> specializations as needed

#endif // __CHARACTERISTICS_H__
 