//////////////////////////////////////////////////////////////////////
// WdmVNICDrv.h 
//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//
// Generated by DriverNetworks Wizard on	Friday, June 02, 2000
//

#ifndef _WdmVNICDrv_h	
#define _WdmVNICDrv_h

#include	<kndis.h>

//////////////////////////////////////////////////////////////////////
// WdmVNICDriver	Declaration
class WdmVNICDriver : public KNdisMiniDriver
{
protected:
	// must implement the entry point
	NTSTATUS DriverEntry(IN PVOID RegistryPath);

};

#endif 