//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
// wdmvnic.cpp - source file generated by NetDrvWizard. Contains
//				  KNdisMiniDriver-derived implementation
//				  

#include <kndis.h>
#include <kndisvdw.h>		  // DriverWorks
#include <KIrpPool.h>
#include "Characteristics.h" 
#include "WdmVNICDrv.h"
#include "WdmVNICAdap.h"

///////////////////////////////////////////////////////////////////
// Begin INIT time code
//
// Code in section INIT is discarded after the driver initializes
//#pragma code_seg("INIT")


// The following macro declares the driver class:

DECLARE_MINIDRIVER_CLASS(WdmVNICDriver)

//////////////////////////////////////////////////////////////////////
// WdmVNICDriver	Implementation

/////////////////////////////////////////////////////////////////////
// WdmVNICDriver::DriverEntry
//
// This method registers adapter characteristics (a handler pointer table)
// with NDIS. Usually that's all this function has to do.
//
// Returns:
//	Status code of registration. Usually, it's NDIS_STATUS_SUCCESS.
//  Returning any other code prevents the driver from being loaded.
NTSTATUS WdmVNICDriver::DriverEntry(IN PVOID)
{
	TRACE("WdmVNICDriver::DriverEntry - built for NDIS %u.%u\n",
		KNdisAdapterTraits<WdmVNICAdapter>::NdisVersionMajor(), 
		KNdisAdapterTraits<WdmVNICAdapter>::NdisVersionMinor()
		);

	KNDIS_MINIPORT_CHARACTERISTICS<WdmVNICAdapter> Chars;
	return	Chars.Register(*this);	
}

 