#############################################################################
#
#	Copyright (C) Microsoft Corporation 1991
#	All Rights Reserved.
#
#	dev\inc16 makefile
#
#	inc.mk contains the rules and dependence list of inc/h files.
#
#############################################################################

ROOT = ..\..
IS_16	= TRUE
IS_DDK = TRUE
TARGETS = $(INC16DEP)
CLEANLIST = $(INC16DEP)

!include ..\master.mk
