all: howl.exe \
	001_helloworld.exe		001x_helloworld.exe		\
	002_button1.exe			002x_button1.exe		\
	003_button2.exe			003x_button2.exe		\
	004_button3.exe			004x_button3.exe		\
	005_checkBox1.exe		005x_checkBox1.exe		\
	006_checkBox2.exe		006x_checkBox2.exe		\
	007_checkBox3.exe		007x_checkBox3.exe		\
	008_checkBox4.exe		008x_checkBox4.exe		\
	009x_radioSet1.exe		009_radioSet1.exe		\
	010x_radioSet2.exe		010_radioSet2.exe		\
	011x_radioSet3.exe		011_radioSet3.exe		\
	012x_label1.exe			012_label1.exe			\
	013x_label2.exe			013_label2.exe			\
	014x_menu1.exe			014_menu1.exe			\
	015x_graphics1.exe		015_graphics1.exe		\
	016x_graphics2.exe		016_graphics2.exe		\
	017x_graphics3.exe		017_graphics3.exe		\
	018x_graphics4.exe		018_graphics4.exe		\
	019x_graphics5.exe		019_graphics5.exe		\
	020x_icons.exe			020_icons.exe			\
	021x_bitmap1.exe		021_bitmap1.exe			\
	022x_edit1.exe			022_edit1.exe			\
	023x_edit2.exe			023_edit2.exe			\
	024x_edit3.exe			024_edit3.exe			\
	025x_edit4.exe			025_edit4.exe			\
	026x_edit5.exe			026_edit5.exe			\
	027x_edit6.exe			027_edit6.exe			\
	028x_edit7.exe			028_edit7.exe			\
	029x_edit8.exe			029_edit8.exe			\
	030x_passwd1.exe		030_passwd1.exe			\
	031x_textEdit1.exe		031_textEdit1.exe		\
	032_textEdit2.exe								\
	033_textEdit3.exe								\
	034_surface1.exe								\
	035_textedit4.exe								\
	036_updown1.exe			036x_updown1.exe		\
	037_updown2.exe			037x_updown2.exe		\
	038_listBox1.exe		038x_listBox1.exe		\
	039_listBox2.exe		039x_listBox2.exe		\
	040_listBox3.exe		040x_listBox3.exe		\
	041_listBox4.exe		041x_listBox4.exe		\
	042_listBox5.exe		042x_listBox5.exe		\
	043_listBox6.exe		043x_listBox6.exe		\
	044_listBox7.exe		044x_listBox7.exe		\
	045_dragListBox1.exe	045x_dragListBox1.exe	\
	046_comboBox1.exe		046x_comboBox1.exe		\
	047_listBox8.exe		047x_listBox8.exe		\
	048_dragListBox2.exe	048x_dragListBox2.exe	\
	049_comboBox2.exe		049x_comboBox2.exe		\
	050_groupBox1.exe		050x_groupBox1.exe		\
	051_progressBar1.exe	051x_progressBar1.exe	\
	052_scrollBar1.exe		052x_scrollBar1.exe		\
	053_trackBar1.exe		053x_trackBar1.exe		\
	054_tabs1.exe									\
	055_timer1.exe			055x_timer1.exe			\
	056_timer2.exe									\
	057_window1.exe									\
	058_thread1.exe									\
	
	
	
	
	
howl.exe: howldemo.obj howlDemo.hhf image.res
	hla -e:howl howldemo.obj image.res
	
image.res:image.rc
	rc image.rc

howldemo.obj:howldemo.hla howldemo.hhf
	hla -@@ -c howldemo.hla



001_helloworld.exe: 001_helloworld.hla
	hla 001_helloworld
	

001x_helloworld.exe: 001x_helloworld.hla
	hla 001x_helloworld
	
	

002_button1.exe: 002_button1.hla
	hla 002_button1
	
002x_button1.exe: 002x_button1.hla
	hla 002x_button1
	


003x_button2.exe: 003x_button2.hla
	hla 003x_button2
	

003_button2.exe: 003_button2.hla
	hla 003_button2
	


004x_button3.exe: 004x_button3.hla
	hla 004x_button3
	

004_button3.exe: 004_button3.hla
	hla 004_button3
	


005x_checkBox1.exe: 005x_checkBox1.hla
	hla 005x_checkBox1
	

005_checkBox1.exe: 005_checkBox1.hla
	hla 005_checkBox1
	


006x_checkBox2.exe: 006x_checkBox2.hla
	hla 006x_checkBox2
	

006_checkBox2.exe: 006_checkBox2.hla
	hla 006_checkBox2
	


007x_checkBox3.exe: 007x_checkBox3.hla
	hla 007x_checkBox3
	

007_checkBox3.exe: 007_checkBox3.hla
	hla 007_checkBox3
	


008x_checkBox4.exe: 008x_checkBox4.hla
	hla 008x_checkBox4
	

008_checkBox4.exe: 008_checkBox4.hla
	hla 008_checkBox4
	


009x_radioSet1.exe: 009x_radioSet1.hla
	hla 009x_radioSet1
	

009_radioSet1.exe: 009_radioSet1.hla
	hla 009_radioSet1
	


010x_radioSet2.exe: 010x_radioSet2.hla
	hla 010x_radioSet2
	

010_radioSet2.exe: 010_radioSet2.hla
	hla 010_radioSet2
	


011x_radioSet3.exe: 011x_radioSet3.hla
	hla 011x_radioSet3
	

011_radioSet3.exe: 011_radioSet3.hla
	hla 011_radioSet3
	


012x_label1.exe: 012x_label1.hla
	hla 012x_label1
	

012_label1.exe: 012_label1.hla
	hla 012_label1
	


013x_label2.exe: 013x_label2.hla
	hla 013x_label2
	

013_label2.exe: 013_label2.hla
	hla 013_label2
	


014x_menu1.exe: 014x_menu1.hla
	hla 014x_menu1
	

014_menu1.exe: 014_menu1.hla
	hla 014_menu1
	


015x_graphics1.exe: 015x_graphics1.hla
	hla 015x_graphics1
	

015_graphics1.exe: 015_graphics1.hla
	hla 015_graphics1
	


016x_graphics2.exe: 016x_graphics2.hla
	hla 016x_graphics2
	

016_graphics2.exe: 016_graphics2.hla
	hla 016_graphics2
	


017x_graphics3.exe: 017x_graphics3.hla
	hla 017x_graphics3
	

017_graphics3.exe: 017_graphics3.hla
	hla 017_graphics3
	


018x_graphics4.exe: 018x_graphics4.hla
	hla 018x_graphics4
	

018_graphics4.exe: 018_graphics4.hla
	hla 018_graphics4
	


019x_graphics5.exe: 019x_graphics5.hla
	hla 019x_graphics5
	

019_graphics5.exe: 019_graphics5.hla
	hla 019_graphics5
	


020x_icons.exe: 020x_icons.hla
	hla 020x_icons
	
020_icons.exe: 020_icons.hla
	hla 020_icons 
	


021x_bitmap1.exe: 021x_bitmap1.hla image.res
	hla 021x_bitmap1 image.res
	
021_bitmap1.exe: 021_bitmap1.hla image.res
	hla 021_bitmap1 image.res 
	


022x_edit1.exe: 022x_edit1.hla
	hla 022x_edit1
	
022_edit1.exe: 022_edit1.hla
	hla 022_edit1 
	


023x_edit2.exe: 023x_edit2.hla
	hla 023x_edit2
	
023_edit2.exe: 023_edit2.hla
	hla 023_edit2 
	


024x_edit3.exe: 024x_edit3.hla
	hla 024x_edit3
	
024_edit3.exe: 024_edit3.hla
	hla 024_edit3 
	


025x_edit4.exe: 025x_edit4.hla
	hla 025x_edit4
	
025_edit4.exe: 025_edit4.hla
	hla 025_edit4 
	


026x_edit5.exe: 026x_edit5.hla
	hla 026x_edit5
	
026_edit5.exe: 026_edit5.hla
	hla 026_edit5 
	


027x_edit6.exe: 027x_edit6.hla
	hla 027x_edit6
	
027_edit6.exe: 027_edit6.hla
	hla 027_edit6 
	


028x_edit7.exe: 028x_edit7.hla
	hla 028x_edit7
	
028_edit7.exe: 028_edit7.hla
	hla 028_edit7 
	


029x_edit8.exe: 029x_edit8.hla
	hla 029x_edit8
	
029_edit8.exe: 029_edit8.hla
	hla 029_edit8 
	


	


030x_passwd1.exe: 030x_passwd1.hla
	hla 030x_passwd1
	
030_passwd1.exe: 030_passwd1.hla
	hla 030_passwd1 
	

031x_textEdit1.exe: 031x_textEdit1.hla
	hla 031x_textEdit1
	
031_textEdit1.exe: 031_textEdit1.hla
	hla 031_textEdit1 
	

	
032_textEdit2.exe: 032_textEdit2.hla
	hla 032_textEdit2 
	
033_textEdit3.exe: 033_textEdit3.hla
	hla 033_textEdit3 
	
034_surface1.exe: 034_surface1.hla
	hla 034_surface1 
	
035_textEdit4.exe: 035_textEdit4.hla
	hla 035_textEdit4 
	

036x_updown1.exe: 036x_updown1.hla
	hla 036x_updown1
	
036_updown1.exe: 036_updown1.hla
	hla 036_updown1 
	

037x_updown2.exe: 037x_updown2.hla
	hla 037x_updown2
	
037_updown2.exe: 037_updown2.hla
	hla 037_updown2 
	

038x_listBox1.exe: 038x_listBox1.hla
	hla 038x_listBox1
	
038_listBox1.exe: 038_listBox1.hla
	hla 038_listBox1 
	

039x_listBox2.exe: 039x_listBox2.hla
	hla 039x_listBox2
	
039_listBox2.exe: 039_listBox2.hla
	hla 039_listBox2 
	

040x_listBox3.exe: 040x_listBox3.hla
	hla 040x_listBox3
	
040_listBox3.exe: 040_listBox3.hla
	hla 040_listBox3 
	

041x_listBox4.exe: 041x_listBox4.hla
	hla 041x_listBox4
	
041_listBox4.exe: 041_listBox4.hla
	hla 041_listBox4 
	

042x_listBox5.exe: 042x_listBox5.hla
	hla 042x_listBox5
	
042_listBox5.exe: 042_listBox5.hla
	hla 042_listBox5 
	

043x_listBox6.exe: 043x_listBox6.hla
	hla 043x_listBox6
	
043_listBox6.exe: 043_listBox6.hla
	hla 043_listBox6 
	

044x_listBox7.exe: 044x_listBox7.hla
	hla 044x_listBox7
	
044_listBox7.exe: 044_listBox7.hla
	hla 044_listBox7 
	

045x_dragListBox1.exe: 045x_dragListBox1.hla
	hla 045x_dragListBox1
	
045_dragListBox1.exe: 045_dragListBox1.hla
	hla 045_dragListBox1 
	

046x_comboBox1.exe: 046x_comboBox1.hla
	hla 046x_comboBox1
	
046_comboBox1.exe: 046_comboBox1.hla
	hla 046_comboBox1 
	hla 045_dragListBox1 
	

047x_listBox8.exe: 047x_listBox8.hla
	hla 047x_listBox8
	
047_listBox8.exe: 047_listBox8.hla
	hla 047_listBox8 
	

048x_dragListBox2.exe: 048x_dragListBox2.hla
	hla 048x_dragListBox2
	
048_dragListBox2.exe: 048_dragListBox2.hla
	hla 048_dragListBox2 
	

049x_comboBox2.exe: 049x_comboBox2.hla
	hla 049x_comboBox2
	
049_comboBox2.exe: 049_comboBox2.hla
	hla 049_comboBox2 
	

	

050x_groupBox1.exe: 050x_groupBox1.hla
	hla 050x_groupBox1
	
050_groupBox1.exe: 050_groupBox1.hla
	hla 050_groupBox1 
	

	

051x_progressBar1.exe: 051x_progressBar1.hla
	hla 051x_progressBar1
	
051_progressBar1.exe: 051_progressBar1.hla
	hla 051_progressBar1 

	

052x_scrollBar1.exe: 052x_scrollBar1.hla
	hla 052x_scrollBar1
	
052_scrollBar1.exe: 052_scrollBar1.hla
	hla 052_scrollBar1 
	

053x_trackBar1.exe: 053x_trackBar1.hla
	hla 053x_trackBar1
	
053_trackBar1.exe: 053_trackBar1.hla
	hla 053_trackBar1 
	

	
054_tabs1.exe: 054_tabs1.hla
	hla 054_tabs1 
	

	

055x_timer1.exe: 055x_timer1.hla
	hla 055x_timer1
	
055_timer1.exe: 055_timer1.hla
	hla 055_timer1 
	
  	
   	  	  
	
056_timer2.exe: 056_timer2.hla
	hla 056_timer2 
	
  
  	
057_window1.exe: 057_window1.hla
	hla 057_window1 
	
  
  	
058_thread1.exe: 058_thread1.hla
	hla 058_thread1 
	
  	
   	  	  
   	   
clean:
	del *.exe
	del *.asm
	del *.obj
	del *.link
	del *.res