//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
// vdev.cpp - source file generated by NetDrvWizard. Contains
//				  KNdisMiniDriver-derived implementation
//				  

#include "VdevDrv.h"
#include "VdevAdap.h"

#if VDEV_EH_DEMO
#include <kexception.h>
#endif

extern KNdisDebugTrace T;
///////////////////////////////////////////////////////////////////
// Begin INIT time code
//
// Code in section INIT is discarded after the driver initializes
//#pragma code_seg("INIT")


// The following macro declares the driver class:

DECLARE_MINIDRIVER_CLASS(VdevDriver)

//////////////////////////////////////////////////////////////////////
// VdevDriver	Implementation

/////////////////////////////////////////////////////////////////////
// VdevDriver::DriverEntry
//
// This method registers adapter characteristics (a handler pointer table)
// with NDIS. Usually that's all this function has to do.
//
// Returns:
//	Status code of registration. Usually, it's NDIS_STATUS_SUCCESS.
//  Returning any other code prevents the driver from being loaded.
NTSTATUS VdevDriver::DriverEntry(IN PVOID)
{
	T.Trace("VdevDriver::DriverEntry\n");

#if VDEV_EH_DEMO
	//
	// Install C++ exception tranlslator.
	// Note that this is an optional operation required only when translation
	// from a Structural Exception is desirable.
	//
	KException::Install();
#endif

	KNDIS_MINIPORT_CHARACTERISTICS<VdevAdapter> Chars;
	return	Chars.Register(*this);	
}

 