!include $(BASEDIR)\inc\master.mk

DEVICE=NIB16C

OBJS=\
$(BIN)\alloc.obj\
$(BIN)\interrup.obj\
$(BIN)\packet.obj\
$(BIN)\request.obj\
$(BIN)\send.obj\
$(BIN)\sonic.obj\
$(BIN)\transfer.obj\
$(BIN)\loopback.obj\
$(BIN)\ndisdev.obj

INCLUDE=$(INCLUDE)

!include ndis.mk
