//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
// file generated by the wizard

#ifndef __CHARACTERISTICS_H__
#define __CHARACTERISTICS_H__

// Declare Optional NDIS MiniportXxx handlers this driver supports

KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, CheckForHang)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, DisableInterrupt)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, EnableInterrupt)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, HandleInterrupt)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, Isr)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, Send)
KNDIS_MINIPORT_HANDLER(NMNE2KAdapter, TransferData)

// Driver version
#define	NMNE2K_VERSION_MAJOR			1
#define	NMNE2K_VERSION_MINOR			0

// OID Constants
#define	NMNE2K_MAX_LOOKAHEAD		(252-NMNE2K_HEADER_SIZE)
#define	NMNE2K_MAX_FRAMESIZE		1500		// w/o header
#define	NMNE2K_MAX_TOTAL_SIZE		1514		// incl. header
#define	NMNE2K_MAX_LINKSPEED		10000000L
#define	NMNE2K_TRANSMIT_BLOCK		256
#define	NMNE2K_RECEIVE_BLOCK		256

#define NMNE2K_TX_BUFFER_SPACE		16000				
#define NMNE2K_RX_BUFFER_SPACE		16000

#define	NMNE2K_VENDOR_DESCRIPTION	"NuMega NE2000-compatible NDIS Miniport Sample Driver"

#define	NMNE2K_MAX_SEND_PACKETS	4

#define	NMNE2K_802_3_MAX_LIST_SIZE	64

// Sizeof ethernet header
#define NMNE2K_HEADER_SIZE			14			

// PnP Support
#define NMNE2K_SUPPORT_PNP		0


#endif // __CHARACTERISTICS_H__
 