# TESTCFSD.MAK - makefile for VxD TESTCFSD

DEVICENAME = TESTCFSD
FRAMEWORK = C
DEBUG = 1
OBJECTS = TESTCFSD.OBJ VOLFUNCS.OBJ HNDLFUNC.OBJ

!include $(VTOOLSD)\include\vtoolsd.mak
!include $(VTOOLSD)\include\vxdtarg.mak

HNDLFUNC.OBJ:	HNDLFUNC.C TESTCFSD.H
TESTCFSD.OBJ:	TESTCFSD.C TESTCFSD.H
VOLFUNCS.OBJ:	VOLFUNCS.C TESTCFSD.H



    
