all:	WinMain ConsoleHello DebugWindow FofX Fonts GDcaps HelloWorld \
		Lines sysmet TabbedText TextAttr CopyModes ExtendedPens FillPaths \
		Rectangles Ellipses Beziers Clover Bitmaps Bitmaps2 Bitmaps3 \
		kbSysmet keytest Polygons Metafiles typewriter MousePts MousePts2 \
		MouseEyes MouseCapture HitTest
		
copy:
	copy wpa.hhf WinMain
	copy wpa.hhf ConsoleHello
	copy wpa.hhf DebugWindow
	copy wpa.hhf FofX
	copy wpa.hhf Fonts
	copy wpa.hhf GDcaps
	copy wpa.hhf HelloWorld
	copy wpa.hhf Lines
	copy wpa.hhf sysmet
	copy wpa.hhf TabbedText
	copy wpa.hhf TextAttr
	copy wpa.hhf CopyModes
	copy wpa.hhf ExtendedPens
	copy wpa.hhf FillPaths
	copy wpa.hhf Rectangles
	copy wpa.hhf Ellipses
	copy wpa.hhf Beziers
	copy wpa.hhf Clover
	copy wpa.hhf Polygons
	copy wpa.hhf Bitmaps
	copy wpa.hhf Bitmaps2
	copy wpa.hhf Bitmaps3
	copy wpa.hhf Metafiles
	copy wpa.hhf kbSysmet
	copy wpa.hhf keytest
	copy wpa.hhf typewriter
	copy wpa.hhf MousePts
	copy wpa.hhf MousePts2
	copy wpa.hhf MouseEyes
	copy wpa.hhf MouseCapture
	copy wpa.hhf HitTest

	copy winmain\winmain.hhf .
	copy winmain\winmain.hhf FofX
	copy winmain\winmain.hhf CopyModes
	copy winmain\winmain.hhf ExtendedPens
	copy winmain\winmain.hhf FillPaths
	copy winmain\winmain.hhf Rectangles
	copy winmain\winmain.hhf Ellipses
	copy winmain\winmain.hhf Beziers
	copy winmain\winmain.hhf Clover
	copy winmain\winmain.hhf Polygons
	copy winmain\winmain.hhf Bitmaps
	copy winmain\winmain.hhf Bitmaps2
	copy winmain\winmain.hhf Bitmaps3
	copy winmain\winmain.hhf Metafiles
	copy winmain\winmain.hhf kbSysmet
	copy winmain\winmain.hhf keytest
	copy winmain\winmain.hhf typewriter
	copy winmain\winmain.hhf MousePts
	copy winmain\winmain.hhf MousePts2
	copy winmain\winmain.hhf MouseEyes
	copy winmain\winmain.hhf MouseCapture
	copy winmain\winmain.hhf HitTest

	copy winmain\winmain.lib .
	copy winmain\winmain.lib FofX
	copy winmain\winmain.lib CopyModes
	copy winmain\winmain.lib ExtendedPens
	copy winmain\winmain.lib FillPaths
	copy winmain\winmain.lib Rectangles
	copy winmain\winmain.lib Ellipses
	copy winmain\winmain.lib Beziers
	copy winmain\winmain.lib Clover
	copy winmain\winmain.lib Polygons
	copy winmain\winmain.lib Bitmaps
	copy winmain\winmain.lib Bitmaps2
	copy winmain\winmain.lib Bitmaps3
	copy winmain\winmain.lib Metafiles
	copy winmain\winmain.lib kbSysmet
	copy winmain\winmain.lib keytest
	copy winmain\winmain.lib typewriter
	copy winmain\winmain.lib MousePts
	copy winmain\winmain.lib MousePts2
	copy winmain\winmain.lib MouseEyes
	copy winmain\winmain.lib MouseCapture
	copy winmain\winmain.lib HitTest

	  

Beziers:
	cd Beziers
	make
	cd ..

Bitmaps:
	cd Bitmaps
	make
	cd ..

Bitmaps2:
	cd Bitmaps2
	make
	cd ..

Bitmaps3:
	cd Bitmaps3
	make
	cd ..

Clover:
	cd Clover
	make
	cd ..

ConsoleHello:
	cd ConsoleHello
	make
	cd ..

CopyModes:
	cd CopyModes
	make
	cd ..

DebugWindow:
	cd DebugWindow
	make
	cd ..

Ellipses:
	cd Ellipses
	make
	cd ..

ExtendedPens:
	cd ExtendedPens
	make
	cd ..

FillPaths:
	cd FillPaths
	make
	cd ..

FofX:
	cd FofX
	make
	cd ..

Fonts:
	cd Fonts
	make
	cd ..

GDcaps:
	cd GDcaps
	make
	cd ..

HelloWorld:
	cd HelloWorld
	make
	cd ..

HitTest:
	cd HitTest
	make
	cd ..

kbSysmet:
	cd kbSysmet
	make
	cd ..

keytest:
	cd keytest
	make
	cd ..

Lines:
	cd Lines
	make
	cd ..

Metafiles:
	cd Metafiles
	make
	cd ..

MouseCapture:
	cd MouseCapture
	make
	cd ..

MousePts:
	cd MousePts
	make
	cd ..

MousePts2:
	cd MousePts2
	make
	cd ..

MouseEyes:
	cd MouseEyes
	make
	cd ..

Rectangles:
	cd Rectangles
	make
	cd ..

Polygons:
	cd Polygons
	make
	cd ..

sysmet:
	cd sysmet
	make
	cd ..

TabbedText:
	cd TabbedText
	make
	cd ..

TextAttr:
	cd TextAttr
	make
	cd ..

typewriter:
	cd typewriter
	make
	cd ..

WinMain:
	cd WinMain
	make
	cd ..

clean:
	cd Beziers
	make clean
	cd ..

	cd Bitmaps
	make clean
	cd ..

	cd Bitmaps2
	make clean
	cd ..

	cd Bitmaps3
	make clean
	cd ..

	cd Clover
	make clean
	cd ..

	cd Bitmaps
	make clean
	cd ..

	cd ConsoleHello
	make clean
	cd ..

	cd CopyModes
	make clean
	cd ..

	cd DebugWindow
	make clean
	cd ..

	cd Ellipses
	make clean
	cd ..

	cd ExtendedPens
	make clean
	cd ..

	cd FillPaths
	make clean
	cd ..

	cd FofX
	make clean
	cd ..

	cd Fonts
	make clean
	cd ..

	cd GDcaps
	make clean
	cd ..

	cd HelloWorld
	make clean
	cd ..

	cd HitTest
	make clean
	cd ..

	cd kbSysmet
	make clean
	cd ..

	cd keytest
	make clean
	cd ..

	cd Lines
	make clean
	cd ..

	cd Metafiles
	make clean
	cd ..

	cd MouseCapture
	make clean
	cd ..

	cd MousePts
	make clean
	cd ..

	cd MousePts2
	make clean
	cd ..

	cd MouseEyes
	make clean
	cd ..

	cd Rectangles
	make clean
	cd ..

	cd Polygons
	make clean
	cd ..

	cd sysmet
	make clean
	cd ..

	cd TabbedText
	make clean
	cd ..

	cd TextAttr
	make clean
	cd ..

	cd typewriter
	make clean
	cd ..

	cd WinMain
	make clean
	cd ..

