// Stream1394.h
//
// Generated by DriverWizard version DriverStudio 2.7.0 (Build 505)
//

#ifndef __Stream1394_h__
#define __Stream1394_h__


// Function Prototypes

NTSTATUS DriverEntry(
	IN PDRIVER_OBJECT  DriverObject,
	IN PUNICODE_STRING RegistryPath
	);

VOID Unload(
	IN PDRIVER_OBJECT DriverObject 
	);


#endif			// __Stream1394_h__
