// IPFilterHookDevice.h
//
// Generated by DriverWizard version DriverStudio 2.0.1 (Build 36)
// Requires Compuware's DriverWorks classes
//

#ifndef __IPFilterHookDevice_h__
#define __IPFilterHookDevice_h__

class IPFilterHookDevice : public KDevice
{
	// Constructors
public:
	SAFE_DESTRUCTORS;
	IPFilterHookDevice(ULONG Unit=0);
	~IPFilterHookDevice();

	// Member Functions
public:
	DEVMEMBER_DISPATCHERS
	NTSTATUS IPFILTERHOOK_IOCTL_SetHook_Handler(KIrp I);
	NTSTATUS IPFILTERHOOK_IOCTL_ClearHook_Handler(KIrp I);

#ifdef __COMMENT_ONLY
	virtual NTSTATUS Close(KIrp I);					// COMMENT_ONLY
	virtual NTSTATUS Create(KIrp I); 				// COMMENT_ONLY
	virtual NTSTATUS DeviceControl(KIrp I);			// COMMENT_ONLY
#endif

	// Member Data
protected:
	// Unit number for this device instance
	ULONG				m_Unit;
	// Used in constructor/destructor to hold registry path
	KUnitizedName *		m_RegPath;
};


#endif		// __IPFilterHookDevice_h__
