// server.h
//
// Generated by DriverWizard version DriverStudio 2.7.0 (Build 554)
// Requires Compuware's DriverWorks classes
//

#ifndef __SERVER_H__
#define __SERVER_H__

#define EOL "\n"

// Global driver trace object
extern	KDebugOnlyTrace	t;

///////////////////////////////////////////////////////////////////////////////////
// Driver class declaration
//
class Server : public KDriver, public KTdiPnpClient
{
	SAFE_DESTRUCTORS
public:
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);

	/////////////////////////////////////////////////////////////////////
	// KTdiPnpClient interface
	virtual VOID OnNetworkReady();
	virtual VOID OnProviderReady(KNdisString& DeviceName);

	virtual VOID OnAddAddress(USHORT AddressType, PVOID Address, KNdisString& DeviceName);
	virtual VOID OnRemoveAddress(USHORT AddressType, PVOID Address, KNdisString& DeviceName);		
	virtual TDI_STATUS OnSetPower(KNdisString& DeviceName,NDIS_DEVICE_POWER_STATE PowerState);
	virtual TDI_STATUS OnQueryPower(KNdisString& DeviceName,NDIS_DEVICE_POWER_STATE PowerState);
	virtual TDI_STATUS OnQueryRemoveDevice(KNdisString& DeviceName);
	virtual TDI_STATUS OnCancelRemoveDevice(KNdisString& DeviceName);
	virtual TDI_STATUS OnReconfigure(KNdisString& DeviceName);

	void AddTdiPnpClient(ServerDevice* pDevice) { m_List.InsertTail(pDevice); }
	void RemoveTdiPnpClient(ServerDevice* pDevice) { m_List.Remove(pDevice); m_Event.Wait(); }

protected:
	int								m_Unit;
	KInterlockedCounter				m_Providers;
	bool							m_bNetworkReady;

	KInterlockedList<ServerDevice>	m_List;
	KEvent							m_Event;
};

#endif // __SERVER_H__
