# HWINTBC4.MAK - makefile for VxD HWINT - Borland Compiler

DEVICENAME = HWINT
FRAMEWORK = CPP
OBJECTS = BELLEVT.OBJ HWINT.OBJ REALCLK.OBJ INIT.OBI

!include $(VTOOLSD)\include\vtoolsd.mak
!include $(VTOOLSD)\include\vxdtarg.mak

HWINT.OBJ:	HWINT.CPP HWINT.H
REALCLK.OBJ:	REALCLK.CPP REALCLK.H
BELLEVT.OBJ:	BELLEVT.CPP BELLEVT.H
INIT.OBI:	INIT.CPP HWINT.H
