#############################################################################
#
#	Microsoft Confidential
#	Copyright (C) Microsoft Corporation 1991
#	All Rights Reserved.
#
#	dev\ddk\inc16 makefile
#
#	inc.mk contains the rules and dependence list of inc/h files.
#
#############################################################################

ROOT = ..\..\..
IS_16	= TRUE
IS_DDK	= TRUE
CLEANLIST = $(DDKINC16DEP)
TARGETS = $(DDKINC16DEP)

!include ..\..\master.mk
