// VCom1394.h
//
// Generated by DriverWizard version DriverStudio 2.7.0 (Build 562)
// Requires Compuware's DriverWorks classes
//

#ifndef __VCOM1394_h__
#define __VCOM1394_h__

#define EOL "\n"

// Global driver trace object
extern  KTrace  t;

class VCom1394 : public KDriver
{
    SAFE_DESTRUCTORS
public:
    virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
    virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);


    int m_Unit;

};

#endif          // __VCOM1394_h__
