//////////////////////////////////////////////////////////////////////
// Characteristics.h: Constants and Specialized Traits of CoIsdn driver
//
//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03063  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
//
// Generated by Network Driver Wizard on Monday, July 22, 2002
//

#ifndef __CHARACTERISTICS_H__
#define __CHARACTERISTICS_H__

// Declare Optional NDIS MiniportXxx handlers this driver supports

#if defined(CARD_REQUEST_ISR)
# if (CARD_REQUEST_ISR == FALSE)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, DisableInterrupt)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, EnableInterrupt)
#endif
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, HandleInterrupt)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, Isr)
#endif

KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, CheckForHang)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, ReturnPacket)

#if (defined(NDIS50_MINIPORT) || defined (NDIS51_MINIPORT))
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, CoActivateVc)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, CoDeactivateVc)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, CoSendPackets)
KNDIS_MINIPORT_HANDLER(CoIsdnAdapter, CoRequest)
#endif

// Driver version
#define	COISDN_VERSION_MAJOR			1
#define	COISDN_VERSION_MINOR			0

// Medium Specific
#define KNDIS_MEDIUM_INCLUDE_WAN		/* forces OID handlers inclusion */
#define KNDIS_MEDIUM_INCLUDE_CO         /* forces OID handlers inclusion */
#define	COISDN_MEDIUM_TYPE			NdisMediumCoWan


#define	COISDN_VENDOR_DESCRIPTION	"COISDN NDIS Miniport Driver"



// TODO: 
// Add other #defines and/or KNdisAdapterTraits<CoIsdnAdapter> specializations as needed

#endif // __CHARACTERISTICS_H__
