//////////////////////////////////////////////////////////////////////
// CoIsdnDrv.h : Interface for the CoISDNDrv class.
//
//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03063  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
//
// Generated by Network Driver Wizard on Monday, July 22, 2002
//

#ifndef _CoIsdnDrv_h	
#define _CoIsdnDrv_h

#include	<kndis.h>

//////////////////////////////////////////////////////////////////////
// CoIsdnDriver	Declaration
class CoIsdnDriver : public KNdisMiniDriver
{
protected:
	// must implement the entry point
	NTSTATUS DriverEntry(IN PVOID RegistryPath);

};

#endif