icztuts:
	hla -masm -@@ -p:tmp -w tut02.hla
	hla -masm -@@ -p:tmp -w tut03.hla
	hla -masm -@@ -p:tmp -w tut04.hla
	hla -masm -@@ -p:tmp -w tut05.hla
	hla -masm -@@ -p:tmp -w tut06.hla
	hla -masm -@@ -p:tmp -w tut07.hla
	hla -masm -@@ -p:tmp -w tut08.hla tut08.rc
	hla -masm -@@ -p:tmp -w tut08b.hla tut08.rc
	hla -masm -@@ -p:tmp -w tut09.hla tut09.rc
	hla -masm -@@ -p:tmp -w tut10_1.hla tut10_1.rc
	hla -masm -@@ -p:tmp -w tut10_2.hla tut10_2.rc
	hla -masm -@@ -p:tmp -w tut11_3.hla tut11_3.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut12.hla tut12.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut13.hla tut13.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut14.hla tut14.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut15.hla tut15.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut16.hla tut16.rc comdlg32.lib
	hla -masm -@@ -p:tmp -w tut17.hla  DLLSkeleton.lib
	hla -masm -@@ -p:tmp -w tut17_2.hla
	hla -masm -@@ -p:tmp -w tut18.hla comctl32.lib
	hla -masm -@@ -p:tmp -w tut19.hla tut19.rc comctl32.lib
	hla -masm -@@ -p:tmp -w tut20.hla
	hla -masm -@@ -p:tmp -w tut21.hla tut21.rc
	hla -masm -@@ -p:tmp -w tut22.hla
	hla -masm -@@ -p:tmp -w tut23.hla shell32.lib
	hla -masm -@@ -p:tmp -w tut24.hla tut24.rc mousehook.lib
	hla -masm -@@ -p:tmp -w tut25.hla tut25.rc
	hla -masm -@@ -p:tmp -w tut26.hla
	hla -masm -@@ -p:tmp -w tut27.hla tut27.rc comctl32.lib
		
	


clean:
	delete *.obj
	delete *.ilk
	delete *.pdb
	delete *.asm
	delete *.bak
	ren msgbox.exe m.e 
	delete *.exe
	ren m.e msgbox.exe
	delete *.link
	delete *.inc
	delete *.res
	delete tmp\*.*
	
















	 
