// NmProt.h
//
//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03063  USA
//
// Copyright (c) 2004 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//

#ifndef __NmProt_h__
#define __NmProt_h__

#include "kndis.h"

#include "KNdisProtocolDriver.h"
#include "NmProtDevice.h"
#include "NmOpenContext.h"

#define EOL "\n"

class NmProt : public KDriver
{
	SAFE_DESTRUCTORS
public:
	// Member functions
	virtual  VOID Unload(VOID);
	virtual  NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);

	// This function is required by the KNdisProtocol framework.
	// Should be generated by the wizard.
	NDIS_HANDLE GetProtocolHandle(KNdisProtocolBinding*) { return m_Protocol; }

protected:
	// Protocol instance we register
	KNdisProtocol	m_Protocol;

	// Control Device instance
	NmProtDevice* m_pDevice;

	// Service/control device name
	static WCHAR sm_wszServiceName[];
};

#endif			// __NmProt_h__
