// plxioctl.h
//
// Define control codes for PLX9056 driver
//

#ifndef __PLXIOCTL_H__
#define __PLXIOCTL_H__


#define PLX9056_IOCTL_READ_MAILBOX			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PLX9056_IOCTL_WRITE_MAILBOX			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // __PLXIOCTL_H__
