// VRead.h
//
// Generated by DriverWizard version DriverStudio 2.7.0 (Build 554)
// Requires Compuware's DriverWorks classes
//

#ifndef __VRead_h__
#define __VRead_h__

#define EOL "\n"

// Global driver trace object
extern	KDebugOnlyTrace	t;

class VRead : public KDriver
{
	SAFE_DESTRUCTORS
public:
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);


	ULONG	m_Unit;
};

#endif			// __VRead_h__
