//=============================================================================
//
// Compuware Corporation
// NuMega Lab
// 9 Townsend West
// Nashua, NH 03060  USA
//
// Copyright (c) 2001 Compuware Corporation. All Rights Reserved.
// Unpublished - rights reserved under the Copyright laws of the
// United States.
//
//=============================================================================
//////////////////////////////////////////////////////////////////////
// ImDelay.cpp - source file generated by NetDrvWizard. Contains
//				  KNdisIMiniDriver-derived implementation
//				  

#include <KNdisFilterWrapper.h>	// required for IM drivers
#include "ImDelayDrv.h"
#include "ImDelayAdap.h"

///////////////////////////////////////////////////////////////////
// Begin INIT time code
//
// Code in section INIT is discarded after the driver initializes
//#pragma code_seg("INIT")

// The wizard inserts the following macro (declares the driver class)

DECLARE_MINIDRIVER_CLASS(ImDelayDriver)


//////////////////////////////////////////////////////////////////////
// ImDelayDriver	Implementation

/////////////////////////////////////////////////////////////////////
// ImDelayDriver::DriverEntry
//
// This method registers adapter characteristics (a handler pointer table)
// with NDIS. Usually that's all this function has to do.
//
// Returns:
//	Status code of registration. Usually, it's NDIS_STATUS_SUCCESS.
//  Returning any other code prevents the driver from being loaded.
NTSTATUS ImDelayDriver::DriverEntry(IN PVOID)
{
	TRACE("ImDelayDriver::DriverEntry\n");

	KNDIS_FILTERDRIVER_CHARACTERISTICS<ImDelayAdapter> Chars;
	return Chars.Register(*this, L"ImDelay");

}

 